import { randomBytes } from 'node:crypto'
import type { Redis } from 'ioredis'
import type { RefreshTokenStore } from '../domain/ports.js'

// RedisRefreshTokenStore — concrete implementation of RefreshTokenStore.
//
// Refresh tokens are opaque random strings (NOT JWTs) bound to a userId.
// Redis gives us:
//   - native TTL (auto-expiration when the refresh window elapses)
//   - O(1) revocation (DEL key)
//   - atomic rotation via a single Lua script (see ROTATE_LUA below)
//
// Key scheme:
//   refresh:<token>  →  userId  (with TTL = REFRESH_TOKEN_TTL_SECONDS)
//
// Rotation must be atomic: between "validate old token" and "issue new
// token + delete old", another request must not be able to reuse the same
// token. A Lua script runs the read/delete/write sequence on the Redis
// server as an indivisible unit, so concurrent attempts cannot interleave.
export interface RedisRefreshTokenStoreOptions {
  redis: Redis
  ttlSeconds: number
}

// Lua script for atomic rotation:
//   KEYS[1] = old refresh key
//   KEYS[2] = new refresh key (already generated by the caller)
//   ARGV[1] = ttl seconds
// Returns the userId string on success, or nil if the old token does not
// exist (already rotated, revoked, or never issued).
const ROTATE_LUA = `
  local user_id = redis.call('GET', KEYS[1])
  if not user_id then
    return nil
  end
  redis.call('DEL', KEYS[1])
  redis.call('SET', KEYS[2], user_id, 'EX', tonumber(ARGV[1]))
  return user_id
`

export class RedisRefreshTokenStore implements RefreshTokenStore {
  constructor(private readonly options: RedisRefreshTokenStoreOptions) {}

  // -------------------------------------------------------------------------
  // issue — create a brand-new refresh token for the given userId.
  //
  // Called by AuthService.login() right after the password has been
  // verified. Generates a fresh opaque token (32 random bytes), stores it
  // in Redis with a TTL, and returns it to the caller so it can be sent
  // back to the client. The client will present this token to /refresh
  // when their access token expires.
  // -------------------------------------------------------------------------
  async issue(userId: string): Promise<string> {
    const token = generateOpaqueToken()
    await this.options.redis.set(keyOf(token), userId, 'EX', this.options.ttlSeconds)
    return token
  }

  // -------------------------------------------------------------------------
  // resolve — look up which user a refresh token belongs to, without
  // mutating it. Returns null if the token does not exist (never issued,
  // expired by TTL, or already revoked).
  //
  // Not used by the current flows (login / refresh / logout do not need a
  // read-only check), but exposed for completeness so admin tooling or
  // future workflows (e.g. session listing) can introspect tokens.
  // -------------------------------------------------------------------------
  async resolve(token: string): Promise<{ userId: string } | null> {
    const userId = await this.options.redis.get(keyOf(token))
    return userId === null ? null : { userId }
  }

  // -------------------------------------------------------------------------
  // rotate — atomically replace an old refresh token with a brand-new one.
  //
  // Called by AuthService.refresh(). The method:
  //   1. Generates a NEW opaque token (different random 32 bytes).
  //   2. Runs the Lua script which, on the Redis server:
  //        - reads the userId bound to the old token
  //        - deletes the old token (it can never be used again)
  //        - stores the new token bound to the same userId, with a fresh TTL
  //   3. Returns the userId AND the new token so the caller can hand it
  //      back to the client.
  //
  // The whole GET / DEL / SET sequence happens atomically inside Redis,
  // closing the race window where two concurrent /refresh calls could
  // both succeed with the same old token. Returns null if the old token
  // is unknown (expired, revoked, or already rotated by a parallel call).
  // -------------------------------------------------------------------------
  async rotate(oldToken: string): Promise<{ userId: string; newToken: string } | null> {
    const newToken = generateOpaqueToken()
    // ioredis types the eval result as `unknown` for safety. The Lua
    // script returns either a string (userId) or nil.
    const result = (await this.options.redis.eval(
      ROTATE_LUA,
      2,
      keyOf(oldToken),
      keyOf(newToken),
      this.options.ttlSeconds.toString(),
    )) as string | null

    return result === null ? null : { userId: result, newToken }
  }

  // -------------------------------------------------------------------------
  // revoke — invalidate a refresh token. Idempotent: deleting a missing
  // key is a no-op, so calling revoke twice (or on a non-existent token)
  // does not throw. Called by AuthService.logout().
  // -------------------------------------------------------------------------
  async revoke(token: string): Promise<void> {
    await this.options.redis.del(keyOf(token))
  }
}

// generateOpaqueToken — produce a cryptographically-strong random string
// suitable as a refresh token. 32 bytes = 256 bits of entropy, encoded
// in URL-safe base64 (~43 characters). Brute-forcing is infeasible.
function generateOpaqueToken(): string {
  return randomBytes(32).toString('base64url')
}

// keyOf — namespace tokens under a single Redis prefix so they don't
// collide with other types of keys this service may store later
// (e.g. rate-limit counters, password-reset codes).
function keyOf(token: string): string {
  return `refresh:${token}`
}
